=== dionyziz/stanford-db/final/1.dtd
<!ELEMENT Cities (City*)>
<!ELEMENT City (Mayor, Neighborhood+)>
<!ATTLIST City Name CDATA #REQUIRED>
<!ELEMENT Mayor (#PCDATA)>
<!ELEMENT Neighborhood (Library | Bookshop)?>
<!ATTLIST Neighborhood Name CDATA #REQUIRED>
<!ELEMENT Library (#PCDATA)>
<!ELEMENT Bookshop (#PCDATA)>

=== dionyziz/stanford-db/final/1.xml
<?xml version='1.0'?>
<!DOCTYPE Cities SYSTEM '1.dtd'>
<?xml-stylesheet type="text/xsl" href="3-xslt.xml"?>
<Cities>
    <City Name="Athens">
        <Mayor>Dionysis</Mayor>
        <Neighborhood Name="Zografou"><Library>Library of Zografou</Library></Neighborhood>
        <Neighborhood Name="Egaleo"><Bookshop>Papasotiriou</Bookshop></Neighborhood>
        <Neighborhood Name="Agia Paraskevi"><Bookshop>Plaisio</Bookshop></Neighborhood>
        <Neighborhood Name="Kaisariani"></Neighborhood>
    </City>
</Cities>
